### ISSUE TITLE
ENOTFOUND with Docker and lite-server

### ISSUE THREAD

**Issue by Plimsky** [chimurai/http-proxy-middleware#128]
### Expected behavior

Hi ! I'm trying to have a docker environnement for an SPA.
2 Containers : 
* Front : Angular2 ➡️ http://docker.local:3000 
* Back : API Symfony3 ➡️ http://docker.local:8000 

`docker.local == localhost`

I'm using `docker-compose`. Here the configuration :

````
version: '2'

services:
  back:
    extends:
      file: docker-compose.common.yml
      service: back
    volumes:
      - ./back:/var/www
    ports:
      - 8000:80
    environment:
      - SYMFONY_ENV=dev
      - SYMFONY_DEBUG=1
  front:
    extends:
      file: docker-compose.common.yml
      service: front
    volumes:
      - ./front:/var/www
    ports:
      - 80:80
      - 3000:3000
````

Thanks to `http-proxy-middleware`, when my Angular app call the API, it should call the Symfony container.

**Example** : 
http://docker.local:3000/api/login_check => http://docker.local:8000/login_check

### Actual behavior

When I test the request (http://docker.local:3000/api/login_check) with DHC or from the app itself I get this :

````
npm start

> angular-blog@1.0.0 start /var/www/app
> tsc && concurrently "tsc -w" "lite-server -c bs-config.js"

[1] [HPM] Proxy created: /api  ->  http://docker.local:8000
[1] [HPM] Subscribed to http-proxy events:  [ 'error', 'close' ]
[1] ** browser-sync config **
[1] { injectChanges: false,
[1]   files: [ './**/*.{html,htm,css,js}' ],
[1]   watchOptions: { ignored: 'node_modules' },
[1]   server: { baseDir: './', middleware: [ [Object], [Function] ] } }
[1] [BS] Access URLs:
[1]  -----------------------------------
[1]        Local: http://localhost:3000
[1]     External: http://172.18.0.3:3000
[1]  -----------------------------------
[1]           UI: http://localhost:3001
[1]  UI External: http://172.18.0.3:3001
[1]  -----------------------------------
[1] [BS] Serving files from: ./
[1] [BS] Watching files...
[1] [HPM] POST /api/login_check -> http://docker.local:8000
[1] [HPM] Error occurred while trying to proxy request 
/api/login_check from docker.local:3000 to http://docker.local:8000 (ENOTFOUND) (https://nodejs.org/api/errors.html#errors_common_system_errors)
````

### Setup

* macOs Sierra : 10.12.1
* http-proxy-middleware: 0.17.2
* server: _lite-server_ : _2.2.2_
* environement: _docker_ : 1.12.3 

#### proxy middleware configuration
```javascript
var proxyMiddleware = require('http-proxy-middleware');

module.exports = {
    server: {
        middleware: {
            1: proxyMiddleware('/api', {
                target: 'http://docker.local:8000',
                changeOrigin: true
            })
        }
    }
};
```

Thank you for the help ! 👍
